version: '2'
services:
  iky_backend:
    build: .
    environment:
      APPLICATION_ENV: Production
    depends_on:
      - mongodb

  iky_gateway:
    build: frontend/
    ports:
        - "8080:80"
    depends_on:
      - iky_backend

  mongodb:
    image: mongo
    ports:
        - "27017:27017"
    hostname: mongodb
    volumes:
      - mongodbdata:/data

volumes:
  mongodbdata:
